var constants = {

	localhost_port : 'http://localhost:8080',
	// contexts
	web_context : 'payz',
	service_context : 'CorpMediaService',

	// constants

	LastDayOfTheMonth : 'Last Day Of The Month',
	ENDOFDAY : 293,
	MAXENDOF_DAY : "100",
	BASIC : 'Basic',
	HRA : 'HRA',
	PF : 'PF Employee',
	Medical : 'Medical Reimbursement',
	Transport : 'Transport Allowance',
	Special_Allowance : 'Special Allowance',
	Professional_Allowance : 'Professional Allowance',
	Travel_Reimbursement : 'Travel Reimbursement',
	Food_Coupons : 'Food Coupons',
	City_Compensatory_Allowance : 'City Compensatory Allowance',
	Daily_Allowance : 'Daily Allowance',
	Employee_Gratuity_contribution : 'Employee Gratuity contribution',

	// controllers
	CompanyInfoController : 'CompanyInfoController',
	CompanyController : 'CompanyController',
	COMP_SIGNATOR : 'CompanySignatorController',
	LookUpController : 'LookUpController',
	CompanyBankController : 'CompanyBankController',
	DepartmentController : 'DepartmentController',
	TimeSheetApprovalChainController : 'TimeSheetApprovalChainController',
	CompanyLocationController : 'CompanyLocationController',
	GeneralSettingsController : 'GeneralSettingsController',
	CompanyRolesController : 'CompanyRolesController',
	TimeSheetApproverChainController : 'TimeSheetApproverChainController',
	TagsController : 'TagsController',
	CategoriesController : 'CategoriesController',
	JobTitlesController : 'JobTitlesController',
	EmployeeController : 'EmployeeController',
	DeductionsController : 'DeductionsController',
	ReimbursementController : 'ReimbursementController',
	BonusesController : 'BonusesController',
	AllowancesController : 'AllowancesController',
	EmployeeTimeSheetController : 'EmployeeTimeSheetController',
	EmployeeLeaveController     : 'EmployeeLeaveController',

	MedicalReimbursementController : 'MedicalReimbursementController',
	CompanyEmpDefaultController : 'CompanyEmpDefaultController',
	TransportAllowanceController : 'TransportAllowanceController',
	ProfessionalAllowanceController : 'ProfessionalAllowanceController',
	TravelReimbursementController : 'TravelReimbursementController',
	CityCompensatoryAllowanceController : 'CityCompensatoryAllowanceController',
	DailyAllowanceController : 'DailyAllowanceController',
	FoodCouponsController : 'FoodCouponsController',
	GratuityContributionController : 'GratuityContributionController',
	CustomAllowanceController : 'CustomAllowanceController',
	PayrollCycleSettingsController : 'PayrollCycleSettingsController',
	PayrollPeriodCalculationController : 'PayrollPeriodCalculationController',
	ClientsController : 'ClientsController',
	BillingRatesController : 'BillingRatesController',
	ReportsController : 'ReportsController',
	ProjectDetailsController : 'ProjectDetailsController',
	TaskBillingController : 'TaskBillingController',
	ShiftsController : 'ShiftsController',
	TaskAssignToHrController : 'TaskAssignToHrController',
	TaskAssignToEmployeeController : 'TaskAssignToEmployeeController',
	ProjectsController : 'ProjectsController',
	CompanyLeavePlanController : 'CompanyLeavePlanController',
	AddLeaveTypeController : 'AddLeaveTypeController',
	CompanyLeaveTypeController : 'CompanyLeaveTypeController',
	ExitSettingsController : 'ExitSettingsController',
	HolidayController : 'HolidayController',
	NotifyController : 'NotifyController',
	ClientWorkHoursController : 'ClientWorkHoursController',
	DeptWorkHoursController : 'DeptWorkHoursController',
	SalaryComponentController : 'SalaryComponentController',
	DesignationController:'DesignationController',
	RunPayRollController : 'RunPayRollController'

};
